### ISSUE TITLE
add `.codeclimate.yml`

### ISSUE THREAD

**Issue by tchklovski** [predictionmachine/pm-gh-actions#25]
see 
ClickUp [task](https://app.clickup.com/t/mz5bk6)

- codeclimate [doc](https://docs.codeclimate.com/docs/advanced-configuration#section-default-checks)
- I think we can allow 400 lines instead of 250
- I think we should enable the following plugins:
- https://docs.codeclimate.com/docs/editorconfig (maybe commented out in yaml for now)
- https://docs.codeclimate.com/docs/pep8 if we are not using separate flake8 / flakehell via reviewdog (flakehell works via pyproject.toml, which is better)
- maybe https://docs.codeclimate.com/docs/sonar-python
- maybe https://docs.codeclimate.com/docs/shellcheck

**Comment by abhishekmishragithub** [comment]
For flakehell, i have created separate issue #42

**Comment by abhishekmishragithub** [comment]
closed by #38 and #43
